import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { revalidatePath } from "next/cache";

export const dynamic = 'force-dynamic'; // Prevent caching
export const maxDuration = 60; // Max allowed for Vercel Hobby tier

export async function GET(request: Request) {
  try {
    const pendingPosts = await prisma.blogPost.findMany({
      where: {
        isAutoGenerated: true,
        generationStatus: "PENDING",
        publishAt: {
          lte: new Date(),
        },
      },
      take: 1, // Only process 1 post per invocation to prevent Vercel 60s timeout
    });

    if (pendingPosts.length === 0) {
      return NextResponse.json({ message: "No pending posts scheduled for now." });
    }

    // Fetch recently published articles to use for dynamic internal linking
    let recentPosts: { title: string; slug: string }[] = [];
    try {
      recentPosts = await prisma.blogPost.findMany({
        where: {
          published: true,
        },
        select: {
          title: true,
          slug: true,
        },
        orderBy: {
          publishAt: "desc",
        },
        take: 10,
      });
    } catch (e) {
      console.error("Failed to query recent posts for internal linking:", e);
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured.");
    }
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

    const results = [];

    for (const post of pendingPosts) {
      let attempts = 0;
      const maxAttempts = 3;
      let success = false;
      let generatedData = null;
      let lastError = null;

      // Construct dynamic internal linking instructions
      let internalLinksGuideline = "";
      if (recentPosts.length > 0) {
        const linksMarkdownList = recentPosts
          .map((p) => `- "${p.title}": Use path "/blog/${p.slug}"`)
          .join("\n");
        internalLinksGuideline = `2. Contextual Blog Interlinking (SEO Anchor Optimization): Organically and contextually link to 1 or 2 of the following published posts using their exact relative paths. Crucially, use keyword-rich, descriptive anchor texts related to the target post topic (e.g. "[automated attendance software](/blog/slug)" or "[HRMS comparison guide](/blog/slug)" or "[recruitment automation guide](/blog/slug)"). Do NOT use generic text like "read this post" or "learn more here":\n${linksMarkdownList}`;
      } else {
        internalLinksGuideline = `2. General Blog Interlinking: If relevant, include a natural link to the main blog section ("/blog") using keyword-rich anchor text like "[HR insights and guides](/blog)".`;
      }

      while (attempts < maxAttempts && !success) {
        try {
          attempts++;
          const prompt = `You are an elite, high-level SEO and GEO expert, and an authoritative HR tech specialist.
Your writing style is highly engaging, sophisticated, and modern. It MUST NOT sound like a generic AI or ChatGPT (strictly avoid phrases like "In today's fast-paced world", "Unlock the potential", "In conclusion", "It's important to remember", "In summary"). Use punchy, confident, and professional language.

Please generate a premium blog post based on the following parameters:
- Title: ${post.title}
- Content Pillar: ${post.contentPillar || "General HR"}
- Geo Target: ${post.targetLocation || "Global"}
- Primary Keyword: ${post.primaryKeyword || "HR technology"}
- Secondary Keywords: ${post.secondaryKeywords || "human resources, software"}
- Target Word Count: ${post.wordCount || "1000"} words

EEAT & WRITING GUIDELINES (To prevent typical AI patterns):
1. EXPERIENTIAL FLOW: Do NOT use a formulaic structure (e.g., "Introduce topic -> Explain concept -> Summarize -> Repeat conclusion"). Write from the perspective of an experienced HR practitioner or founder.
2. SPECIFIC SCENARIOS: Incorporate concrete, realistic, and specific examples to illustrate your points. (For example: "A retail chain with 120 frontline employees in Delhi..." or "A 50-person SaaS startup with teams in Melbourne and Singapore"). Use specific numbers, times, and roles.
3. GEO COMPLIANCE & LOCAL LABOUR LAWS: Contextually align any compliance or administrative discussions with local laws based on the Geo Target (${post.targetLocation || "Global"}):
   - India: Reference Provident Fund (PF), Employee State Insurance (ESI), TDS calculations, and the Digital Personal Data Protection Act (DPDPA 2023).
   - UAE: Reference Wage Protection System (WPS), Ministry of Human Resources & Emiratisation (MOHRE), and End of Service Gratuity.
   - Qatar: Reference Qatar Labour Law, WPS compliance, and Qatar National Vision.
   - Australia: Reference Single Touch Payroll (STP), Fair Work Act, and Superannuation contributions.
   - Global/Other: Reference GDPR, FLSA, or standard regional guidelines where applicable.
4. ACTIONABLE INSIGHTS: Provide concrete implementation checklists, bulleted frameworks, or "common pitfalls to avoid" that business leaders can execute immediately.

FORMATTING & GEO (Generative Engine Optimization) RULES:
1. Optimize for AI Search (GEO): Provide a clear, direct, and authoritative answer to the core topic in the first 2 paragraphs. AI search engines (Perplexity, ChatGPT) prioritize fluff-free, direct answers.
2. Include Data & Statistics: Incorporate highly realistic industry statistics (e.g., "Data shows a 40% reduction in admin time...") to build authority and trust for AI parsers.
3. Clear Headings: Use highly descriptive Markdown headings (H2, H3) that directly answer user intent.
4. Excellent visual hierarchy: Use short paragraphs (2-3 sentences max) and bulleted/numbered lists where appropriate.
5. Use proper Markdown spacing (ensure blank lines between paragraphs, headers, and lists).
6. Use bolding strategically for emphasis and scannability.
7. Do NOT include the Title as an H1 at the top of the content. Start directly with an engaging hook.

LINKING RULES (SEO Anchor Text Optimization):
1. Job Portal Link: You MUST organically include at least one contextual markdown link to our job portal (https://jobs.airbornehrs.in/jobs) within the text. The anchor text for this link MUST use descriptive, high-value keywords like "HRMS", "AI HR", "HR Tech", "HR Software", "AI Recruitment Portal", or "Employee Management Platform" (for example, "[AI-powered HRMS](https://jobs.airbornehrs.in/jobs)" or "[advanced HR Tech platform](https://jobs.airbornehrs.in/jobs)"). Do NOT use generic text like "click here" or "link".
${internalLinksGuideline}

Return the response STRICTLY as a JSON object with the following structure:
{
  "content": "The full markdown formatted content here. Follow all FORMATTING, EEAT, and LINKING RULES.",
  "summary": "A concise 2-3 sentence summary snippet for search engines.",
  "seoTitle": "Optimized SEO Meta Title (under 60 characters)",
  "seoDescription": "Optimized SEO Meta Description (under 160 characters)",
  "keywords": "Comma-separated list of keywords based on the primary and secondary keywords"
}`;

          const result = await model.generateContent({
            contents: [{ role: "user", parts: [{ text: prompt }] }],
            generationConfig: {
              responseMimeType: "application/json",
            }
          });

          const responseText = result.response.text();
          let cleanedText = responseText.trim();
          if (cleanedText.startsWith("```json")) {
            cleanedText = cleanedText.replace(/^```json\s*/i, "").replace(/\s*```$/, "");
          } else if (cleanedText.startsWith("```")) {
            cleanedText = cleanedText.replace(/^```\s*/, "").replace(/\s*```$/, "");
          }
          generatedData = JSON.parse(cleanedText);
          success = true;
        } catch (err: any) {
          lastError = err;
          console.warn(`Attempt ${attempts} failed for post ${post.id}:`, err.message || err);
          if (attempts < maxAttempts) {
            const delay = attempts * 5000;
            console.log(`Retrying in ${delay / 1000}s...`);
            await new Promise((resolve) => setTimeout(resolve, delay));
          }
        }
      }

      if (success && generatedData) {
        try {
          await prisma.blogPost.update({
            where: { id: post.id },
            data: {
              content: generatedData.content,
              summary: generatedData.summary,
              seoTitle: generatedData.seoTitle,
              seoDescription: generatedData.seoDescription,
              keywords: generatedData.keywords,
              generationStatus: "COMPLETED",
              published: true,
              publishAt: new Date(),
            },
          });

          results.push({ id: post.id, title: post.title, status: "success" });

          // IndexNow API Ping
          try {
            const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://airbornehrs.in";
            const postUrl = `${siteUrl}/blog/${post.slug}`;
            const indexNowKey = process.env.INDEXNOW_KEY || "71701e4a179549cd9da1ce73b9cece41";
            const host = siteUrl.replace(/^https?:\/\//, ""); // strip http:// or https://

            await fetch("https://api.indexnow.org/indexnow", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "charset": "utf-8"
              },
              body: JSON.stringify({
                host: host,
                key: indexNowKey,
                keyLocation: `${siteUrl}/${indexNowKey}.txt`,
                urlList: [postUrl],
              }),
            });
            console.log("IndexNow Ping Successful for:", postUrl);
          } catch (indexNowErr) {
            console.error("IndexNow Ping failed:", indexNowErr);
          }

          // Send NTFY Notification
          try {
            const topic = process.env.NTFY_TOPIC || "airborne_blogs_live";
            const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://airbornehrs.in";
            await fetch(`https://ntfy.sh/${topic}`, {
              method: "POST",
              body: `New Blog Live: ${post.title}\n\nRead it here: ${siteUrl}/blog/${post.slug}`,
              headers: {
                "Title": "Airborne Blog Live",
                "Tags": "loudspeaker,rocket,airborne",
                "Priority": "high",
                "Click": `${siteUrl}/blog/${post.slug}`
              }
            });
          } catch (notifyError) {
            console.error("Failed to send ntfy blog notification:", notifyError);
          }
          const webhookUrl = process.env.ZAPIER_WEBHOOK_URL || process.env.BLOG_WEBHOOK_URL;
          if (webhookUrl) {
            try {
              await fetch(webhookUrl, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                  event: "blog_published",
                  id: post.id,
                  title: post.title,
                  slug: post.slug,
                  summary: generatedData.summary,
                  url: `${process.env.NEXT_PUBLIC_SITE_URL || "https://airbornehrs.in"}/blog/${post.slug}`,
                  imageUrl: `${process.env.NEXT_PUBLIC_SITE_URL || "https://airbornehrs.in"}/api/og?title=${encodeURIComponent(post.title)}&pillar=${encodeURIComponent(post.contentPillar || 'HR Automation')}`
                })
              });
              console.log("Zapier Webhook triggered for post:", post.title);
            } catch (e) {
              console.error("Zapier Webhook setup error:", e);
            }
          }
        } catch (dbErr: any) {
          console.error(`Database update failed for post ${post.id}:`, dbErr);
          results.push({ id: post.id, title: post.title, status: "failed", error: `DB Error: ${dbErr.message}` });
        }
      } else {
        console.error(`Failed to generate post ${post.id} after ${maxAttempts} attempts:`, lastError);
        try {
          await prisma.blogPost.update({
            where: { id: post.id },
            data: { generationStatus: "FAILED" },
          });
        } catch (dbErr) {
          console.error("Failed to mark post status as FAILED in DB:", dbErr);
        }
        results.push({ id: post.id, title: post.title, status: "failed", error: lastError?.message || "Generation failed" });
      }

      // Add a small delay between generations to prevent hitting Gemini API rate limits/concurrency spikes
      await new Promise((resolve) => setTimeout(resolve, 6000));
    }

    revalidatePath("/admin-portal-xyz");
    revalidatePath("/");
    revalidatePath("/sitemap.xml");
    
    return NextResponse.json({ message: "Processed scheduled posts", results });
  } catch (error: any) {
    console.error("Cron Job Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
