import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { revalidatePath } from "next/cache";

export const dynamic = 'force-dynamic'; // Prevent caching

export async function GET(request: Request) {
  try {
    const pendingPosts = await prisma.blogPost.findMany({
      where: {
        isAutoGenerated: true,
        generationStatus: "PENDING",
        publishAt: {
          lte: new Date(),
        },
      },
      take: 5, // Batch processing to prevent serverless timeouts
    });

    if (pendingPosts.length === 0) {
      return NextResponse.json({ message: "No pending posts scheduled for now." });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured.");
    }
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const results = [];

    for (const post of pendingPosts) {
      try {
        const prompt = `You are an expert SEO content writer and HR tech specialist.
Please generate a blog post based on the following parameters:
- Title: ${post.title}
- Content Pillar: ${post.contentPillar || "General HR"}
- Geo Target: ${post.targetLocation || "Global"}
- Primary Keyword: ${post.primaryKeyword || "HR technology"}
- Secondary Keywords: ${post.secondaryKeywords || "human resources, software"}
- Target Word Count: ${post.wordCount || "1000"} words

Return the response STRICTLY as a JSON object with the following structure:
{
  "content": "The full markdown formatted content here (do not include the title as an H1). Use proper markdown headings (##, ###), bullet points, and formatting.",
  "summary": "A concise 2-3 sentence summary snippet for search engines.",
  "seoTitle": "Optimized SEO Meta Title (under 60 characters)",
  "seoDescription": "Optimized SEO Meta Description (under 160 characters)",
  "keywords": "Comma-separated list of keywords based on the primary and secondary keywords"
}
Ensure the JSON is valid and escaped properly. Do not wrap the JSON in markdown blocks like \`\`\`json, just return the raw JSON object.`;

        const result = await model.generateContent(prompt);
        const responseText = result.response.text();
        const cleanJson = responseText.replace(/^```(json)?\s*/i, '').replace(/\s*```$/, '').trim();
        const generatedData = JSON.parse(cleanJson);

        await prisma.blogPost.update({
          where: { id: post.id },
          data: {
            content: generatedData.content,
            summary: generatedData.summary,
            seoTitle: generatedData.seoTitle,
            seoDescription: generatedData.seoDescription,
            keywords: generatedData.keywords,
            generationStatus: "COMPLETED",
            published: true, // Auto-publish upon successful generation
          },
        });

        results.push({ id: post.id, title: post.title, status: "success" });
      } catch (err: any) {
        console.error(`Failed to generate post ${post.id}:`, err);
        // Mark as FAILED so it doesn't get stuck in an infinite retry loop
        await prisma.blogPost.update({
          where: { id: post.id },
          data: { generationStatus: "FAILED" },
        });
        results.push({ id: post.id, title: post.title, status: "failed", error: err.message });
      }
    }

    revalidatePath("/admin-portal-xyz");
    revalidatePath("/");
    revalidatePath("/sitemap.xml");
    
    return NextResponse.json({ message: "Processed scheduled posts", results });
  } catch (error: any) {
    console.error("Cron Job Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
