const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function run() {
  const now = new Date();
  console.log('Current local Date:', now.toISOString());
  const pending = await prisma.blogPost.findMany({
    where: {
      isAutoGenerated: true,
      generationStatus: "PENDING"
    }
  });
  console.log('All pending auto-generated posts:');
  pending.forEach(p => {
    console.log(`- Title: ${p.title}\n  Slug: ${p.slug}\n  publishAt: ${p.publishAt.toISOString()}\n  lte now?: ${p.publishAt <= now}`);
  });
}
run().finally(() => prisma.$disconnect());
