import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const posts = await prisma.blogPost.findMany({
    where: {
      isAutoGenerated: true,
      publishAt: {
        gte: new Date('2026-06-10T00:00:00.000Z'),
        lt: new Date('2026-06-12T00:00:00.000Z')
      }
    }
  });
  console.log('Posts for 10th and 11th:', posts.map(p => ({
    id: p.id,
    title: p.title,
    publishAt: p.publishAt,
    status: p.generationStatus,
    published: p.published
  })));
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
